---
format: gfm
---

# registers2parquet: Converting the DST data into Parquet files

<!-- badges: start -->

<!-- badges: end -->

The goal of registers2parquet is to take the mess of DST SAS files and convert
them into something more modern, faster, and easier to work with. And
also to prepare the data for our own work.

Want to review the documentation? See the PDF file in the `docs/` folder
by opening the `docs/manual.pdf` file to check out the documentation.
There are sections on "Saving as Parquet" for the code used to save the
data and for reasons on why we're using this format as well as
"Importing Parquet" for examples on how to work with this format and how
to use a language (DuckDB SQL) to do your work faster.

## For Luke

To rebuild the datasets, run the targets pipeline with the RStudio addin
(from the Palette) or with `targets::tar_make()`. Or open Git Bash and
run `sh run.sh`. You might have to run the pipeline a few times in order
to build all the targets.
